name: Contributor Issue Form
description: Use this form to submit issues related to **Scam Website**
title: '[ENTER ISSUE TITLE]'
labels: ['needs triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to contribute to Scam Website! Please fill out the following fields to help us understand and address your issue effectively.

  - type: input
    id: issue_name
    attributes:
      label: 'ISSUE NAME'
      description: 'A short and descriptive title for your issue.'
      placeholder: 'e.g., Improve UI features'
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: 'ISSUE DESCRIPTION'
      description: 'Provide a detailed description of the issue.'
      placeholder: 'Describe the problem, steps to reproduce, and any other relevant information.'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        Thank you for raising this issue! We will review your issue and get back to you shortly.
